export const ORDER_CREATE_REQUEST = "PLACE_ORDER_REQUEST";
export const ORDER_CREATE_SUCCESS = "PLACE_ORDER_SUCCESS";
export const ORDER_CREATE_FAIL = "PLACE_ORDER_FAIL";

export const GET_ORDER_LIST_REQUEST = "GET_ORDER_LIST_REQUEST";
export const GET_ORDER_LIST_SUCCESS = "GET_ORDER_LIST_SUCCESS";
export const GET_ORDER_LIST_FAIL = "GET_ORDER_LIST_FAIL";

export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST";
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS";
export const ORDER_DETAILS_FAIL = "ORDER_DETAILS_FAIL";

export const ORDER_PAY_REQUEST = "ORDER_PAY_REQUEST";
export const ORDER_PAY_SUCCESS = "ORDER_PAY_SUCCESS";
export const ORDER_PAY_FAIL = "ORDER_PAY_FAIL";
export const ORDER_PAY_RESET = "ORDER_PAY_RESET";

export const ORDER_LIST_MY_REQUEST = "ORDER_LIST_MY_REQUEST";
export const ORDER_LIST_MY_SUCCESS = "ORDER_LIST_MY_SUCCESS";
export const ORDER_LIST_MY_FAIL = "ORDER_LIST_MY_FAIL";
export const ORDER_LIST_MY_RESET = "ORDER_LIST_MY_RESET";

export const ORDER_DELEVERY_REQUEST = "ORDER_DELEVERY_REQUEST";
export const ORDER_DELEVERY_SUCCESS = "ORDER_DELEVERY_SUCCESS";
export const ORDER_DELEVERY_FAIL = "ORDER_DELEVERY_FAIL";
export const ORDER_DELEVERY_RESET = "ORDER_DELEVERY_RESET";
